package com.cagri.hrms.mapper;

import com.cagri.hrms.dto.request.employee.LeaveRequestDTO;
import com.cagri.hrms.dto.response.employee.LeaveResponseDTO;
import com.cagri.hrms.entity.employee.Leave;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface LeaveMapper {

    @Mapping(target = "id", ignore = true) // ID is auto-generated by the database
    @Mapping(target = "status", ignore = true) // Status will be manually set in the service
    @Mapping(target = "employee", ignore = true) // Employee is fetched from repository
    @Mapping(target = "leaveDefinition", ignore = true) // LeaveDefinition is fetched from repository
    @Mapping(target = "requestDate", ignore = true) // Set during request creation
    @Mapping(target = "decisionDate", ignore = true)
    @Mapping(target = "managerNote", ignore = true)
    Leave toEntity(LeaveRequestDTO dto);

    @Mapping(source = "employee.id", target = "employeeId")
    @Mapping(source = "employee.user.fullName", target = "employeeFullName")
    @Mapping(source = "leaveDefinition.name", target = "leaveDefinitionName")
    LeaveResponseDTO toDto(Leave leave);
}
