package com.cagri.hrms.enums;

public enum EventType {
    ASSIGNED, CONFIRMED, RETURN_REQUESTED, RETURN_COMPLETED,
    STATUS_CHANGED, CONDITION_CHANGED,
    MAINTENANCE_OPENED, MAINTENANCE_CLOSED,
    ISSUE_REPORTED, LOST_REPORTED, NOTE_ADDED, ISSUE_CONFIRMED,
    RETURN_REQUEST_CANCELED,     // NEW: employee undoes return request
    ISSUE_CANCELED               // NEW: employee undoes issue report (MAINTENANCE/LOST)
}
